@startuml

[Message Queue] as MQ
[DataBase] as DB

[Sensor #1] --> MQ
[Sensor #2] --> MQ
[Sensor #3] --> MQ

MQ --> [Analyzer #1]
MQ --> [Analyzer #2]
MQ --> [Analyzer #3]

[Analyzer #1] --> DB
[Analyzer #2] --> DB
[Analyzer #3] --> DB

@enduml