@startuml

[DataBase] as DB
[Blob Storage] as BS

[Load Balancer] as LB
[Gateway #1] as G1
[Gateway #2] as G2

[Message Queue] as MQ

[Client #1] as C1
[Client #2] as C2
[Client #3] as C3

[Prediction Service #1] as PS1
[Prediction Service #2] as PS2

C1 --> LB
C2 --> LB
C3 --> LB

LB --> G1
LB --> G2

G1 --> BS
G2 --> BS
G1 --> MQ
G2 --> MQ

MQ --> PS1
MQ --> PS2

BS --> PS1
BS --> PS2

PS1 --> DB
PS2 --> DB

@enduml